namespace: frr
name: notepadpp
version: 1.0.0
readme: README.md
authors:
  - FRR-Development-Support <FRR-Development-Support@wolterskluwer.com>
  - Herman van der Merwe <Herman.Merwe@wolterskluwer.com>
description: |
  Ansible collection for NotePad++
tags:
  - notepad++
  - windows
dependencies:
  ansible.windows: ">=1.3.0,<2.0.0"
repository: https://bitbucket.wolterskluwer.io/scm/frr-dep-a/ans_notepadpp.git
documentation: https://bitbucket.wolterskluwer.io/scm/frr-dep-a/ans_notepadpp.git
homepage: https://bitbucket.wolterskluwer.io/scm/frr-dep-a/ans_notepadpp.git
issues: https://findit.wkfs-frc.local/projects/DS/issues
build_ignore: []